ALTER DATABASE NANOSPRINGS_SYS SET SINGLE_USER WITH ROLLBACK IMMEDIATE ----->>burda tek kullanýcý moduna çekiyoruz.
GO
alter database NANOSPRINGS_SYS MODIFY NAME= NANOSTS

ALTER DATABASE NANOSTS SET MULTI_USER WITH ROLLBACK IMMEDIATE ----->>burda eski moduna çekiyoruz.

GO